zap_config:
  filename: "tmp/log"
  max_size: 5
  max_age: 400
  max_backups: 1000

userdatabase:
  mysql:
    addr: localhost
    port: 3306
    username: root
    password: 123awzsex
    db: test
    charset: utf8mb4
    connMaxIdleTime: 1h
    connMaxLifeTime: 1h
    place: Asia%2FShanghai
    maxIdleConns: 10
    maxOpenConns: 5
  redis1:
    address: localhost
    port: 6379
    password: 123awzsex
    connMaxIdleTime: 1h
    connMaxLifeTime: 1h
    maxIdleConns: 10
    maxOpenConns: 5
  redis2:
    address: localhost
    port: 26379
    password: 123awzsex
    connMaxIdleTime: 1h
    connMaxLifeTime: 1h
    maxIdleConns: 10
    maxOpenConns: 5

shopdatabase:
  mysql:
    addr: localhost
    port: 3307
    username: root
    password: root
    db: test
    charset: utf8mb4
    connMaxIdleTime: 1h
    connMaxLifeTime: 1h
    place: Asia%2FShanghai
    maxIdleConns: 10
    maxOpenConns: 5
  redis1:
    address: localhost
    port: 6380
    password: root
    connMaxIdleTime: 1h
    connMaxLifeTime: 1h
    maxIdleConns: 10
    maxOpenConns: 5
  redis2:
    address: localhost
    port: 26380
    password: root
    connMaxIdleTime: 1h
    connMaxLifeTime: 1h
    maxIdleConns: 10
    maxOpenConns: 5
server:
  host: localhost
  port: 8080
  mode: debug

zookeeper:
  servers:
    - "localhost"  # 使用容器名称
  timeout: 5

kafka:
  brokers:
    - "localhost:29092"
    - "localhost:29093"
    - "localhost:29094"

etcd:
  endpoints:
    - http://localhost:2379

jaeger:
  endpoint: http://localhost:16686/


nginx:
  address: localhost
  port: 80
