zap_config:
  filename: "tmp/log"
  max_size: 5
  max_age: 400
  max_backups: 1000

database:
  mysql:
    addr: localhost
    port: 3306
    username: root
    password: 123awzsex
    db: test
    charset: utf8mb4
    connMaxIdleTime: 1h
    connMaxLifeTime: 1h
    place: Asia%2FShanghai
    maxIdleConns: 10
    maxOpenConns: 5
  redis:
    address: localhost
    port: 6379
    password: 123awzsex
    connMaxIdleTime: 1h
    connMaxLifeTime: 1h
    maxIdleConns: 10
    maxOpenConns: 5

server:
  host: localhost
  port: 8080
  mode: debug

zookeeper:
  address: localhost:2181

kafka:
  brokers:
    - localhost:9092
    - localhost:9093
    - localhost:9094

etcd:
  endpoints:
    - http://localhost:2379

jaeger:
  endpoint: http://localhost:16686/


nginx:
  address: localhost
  port: 80
