###创建订单
POST http://localhost:8082/pay/order/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTgzMDczMTQsInVzZXJuYW1lIjoianpyIn0.1REATy7boJ1cgB5XZP6TPb_YQIkDB95Z7HDSol9hbEg

{
  "productId": 15,
  "buyQuantity": 2
}
###获取订单
GET http://localhost:8082/pay/order/get?orderId=8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTgzMDczMTQsInVzZXJuYW1lIjoianpyIn0.1REATy7boJ1cgB5XZP6TPb_YQIkDB95Z7HDSol9hbEg


###支付订单
POST http://localhost:8082/pay/order/payment HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTgzMDczMTQsInVzZXJuYW1lIjoianpyIn0.1REATy7boJ1cgB5XZP6TPb_YQIkDB95Z7HDSol9hbEg

{
  "orderId": 8
}

###使用优惠券
POST http://localhost:8082/pay/order/usecoupon HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTgzMDczMTQsInVzZXJuYW1lIjoianpyIn0.1REATy7boJ1cgB5XZP6TPb_YQIkDB95Z7HDSol9hbEg

{
  "coupon": 0.8,
  "orderId": 8
}

###删除订单
DELETE http://localhost:8082/pay/order/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTgzMDY1MzksInVzZXJuYW1lIjoianpyIn0.glR60OxoAu_bLXp3xFGbzrBEo_8K0GVfA4ZYI5sCTH0

{
  "orderId": 7
}

###秒杀商品请求
POST http://localhost:8082/pay/seckill/request HTTP/1.1
Content-Type: application/json

{
  "ProductId": 1,
  "BuyQuantity": 2
}

###秒杀商品结果
POST http://localhost:8082/pay/seckill/result HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTgzMDczMTQsInVzZXJuYW1lIjoianpyIn0.1REATy7boJ1cgB5XZP6TPb_YQIkDB95Z7HDSol9hbEg

{
  "productId": 15
}

