// Code generated by goctl. DO NOT EDIT.
package types

type Product struct {
	Id          string  `json:"id"`          // 商品ID根据kafka消息交互mysql自增键生成
	Name        string  `json:"name"`        // 商品名称
	Description string  `json:"description"` // 商品描述
	Price       float64 `json:"price"`       // 商品价格
	Stock       int     `json:"stock"`       // 商品库存
	Boss        string  `json:"boss"`        // 商品所属
}

type AddProductReq struct {
	Name        string  `json:"name"`        // 商品名称
	Description string  `json:"description"` // 商品描述
	Price       float64 `json:"price"`       // 商品价格
	Stock       int     `json:"stock"`       // 商品库存
	Boss        string  `json:"boss"`        // 商品所属
}

type GetProductReq struct {
	Id string `json:"id"` // 传入商品ID获取单个商品
}

type RefreshProductsReq struct {
}

type CommonResply struct {
	Code    int64  `json:"Code"`
	Message string `json:"Message"`
	Data    string `json:"Data"`
}
