// Code generated by goctl. DO NOT EDIT.
package types

type Product struct {
	Id          int  `json:"id"`          // 商品ID根据kafka消息交互mysql自增键生成
	Name        string  `json:"Name"`        // 商品名称
	Description string  `json:"Description"` // 商品描述
	Price       float64 `json:"Price"`       // 商品价格
	Stock       int     `json:"Stock"`       // 商品库存
	Boss        string  `json:"Boss"`        // 商品所属
}

type AddProductReq struct {
	Name        string  `json:"Name"`        // 商品名称
	Description string  `json:"Description"` // 商品描述
	Price       float64 `json:"Price"`       // 商品价格
	Stock       int     `json:"Stock"`       // 商品库存
	Boss        string  `json:"Boss"`        // 商品所属
}

type GetProductReq struct {
	Id int `json:"id" ` // 传入商品ID获取单个商品
}

type RefreshProductsReq struct {
}

type CommonResply struct {
	Code    int64  `json:"Code"`
	Message string `json:"Message"`
	Data    string `json:"Data"`
}
type RefreshProductsResply struct {
	Code    int64  `json:"Code"`
	Message string `json:"Message"`
	Data    []Product `json:"Data"`
}