// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {//用户注册信息
	UserName string `json:"UserName"` // 用户名
	PassWord string `json:"PassWord"` // 用户密码，MD5加密
	UserNick string `json:"UserNick"` // 用户昵称
	UserIdentity string `json:"UserIdentity"` // 用户身份唯一标识
}

type LoginReq struct {
	UserName string `json:"UserName"` // 用户名
	PassWord string `json:"PassWord"` // 用户密码，MD5加密
}

type UserInfoReq struct {
}

type UserInfoResply struct {
	Code    int64         `json:"Code"`
	Message string        `json:"Message"`
	Data    *UserInfoItem `json:"Data"`
}

type UserInfoItem struct {
	UserIdentity string `json:"UserIdentity"` // 用户身份唯一标识
	UserName     string `json:"UserName"`     // 用户名
	PassWord     string `json:"PassWord"`     // 用户密码
	UserNick     string `json:"UserNick"`     // 用户昵称
	Balance      float64 `json:"Balance"`     // 余额
}

type CommonResply struct {
	Code    int64  `json:"Code"`     //回复码
	Message string `json:"Message"`  //消息
	Data    string `json:"Data"`     //数据
}
