// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"dianshang/testapp/Shop/middleware"
	"net/http"

	"dianshang/testapp/Shop/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/shop/addproduct",
				Handler: middleware.JWTAuthMiddleware(AddProductHandler(serverCtx)),
			},
			{
				Method:  http.MethodGet,
				Path:    "/shop/getproduct",
				Handler: middleware.JWTAuthMiddleware(GetProductHandler(serverCtx)),
			},
			{
				Method:  http.MethodGet,
				Path:    "/shop/refreshproducts",
				Handler: middleware.JWTAuthMiddleware(RefreshProductsHandler(serverCtx)),
			},
		},
	)
}
