// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"dianshang/testapp/Shop/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/addproduct",
				Handler: AddProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/getproduct",
				Handler: GetProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/refreshproducts",
				Handler: RefreshProductsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
